#Specify the read length of the fastq files
read_length: 101

# Give the execution path of picard and gatk
# You may want to increase the memory available
# to java with
# "java -Xmx50G -jar GenomeAnalysisTK.jar"
gatk_path: "java -Xms256M -Xmx50G -jar GenomeAnalysisTK.jar"
picard_path: "java -Xms256M -Xmx50G -jar picard.jar"

# Set the working directory (wd)
wd: test
tmp_dir: tmp

# You must create and populate these directories in your
# working directory (wd) with the starting files.
# Symbolic links should work.
# Please see the README for details
fastq_dir: 0.fastq
refgen_dir: 0.reference_genome_fasta
gencode_dir: 0.gencode
vcf_dir: 0.vcf


# These directories will be created
# as the workflow executes.
snp_dir: 01.snps
star_genome_dir: 01.star_genome
sam_dir: 02.sam_dir
add_rg_dir: 03.add_read_groups
mark_dups_dir: 04.mark_duplicates
find_snps_dir: 05.find_intersecting_snps
remap_dir: 06.remap_dir
remap_add_rg_dir: 07.remap_add_read_groups
remap_mark_dups_dir: 08.remap_mark_duplicates
filter_remapped_reads: 09.filter_remapped_reads
merged_dir: 10.merged_wasp_bam
sorted_dir: 11.sorted_bam
read_counts_dir: 12.final_read_counts


# Extra rule configurations
star_genome_threads: 12
star_align_threads: 6
